# Generated by Django 3.1.3 on 2020-11-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_select',
            field=models.BooleanField(null=True),
        ),
    ]
