# Generated by Django 3.1.3 on 2020-11-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase1', '0002_filemodel_file_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='file_select',
        ),
    ]
